In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
array = np.array([[133,184,248,110],
                  [25,38,165,210],
                  [209,168,204,21],
                  [208,132,116,34]],dtype=np.uint8)

# dst = cv2.medianBlur(array,ksize=3)
# print(dst)
ksize = 3
pad_width = ksize // 2
padded_array = np.pad(array, pad_width, mode='constant', constant_values=0)

# Apply median blur
blurred_padded = cv2.medianBlur(padded_array, ksize=ksize)

# Crop the padded result back to the original size
dst = blurred_padded[pad_width:-pad_width, pad_width:-pad_width]

print(dst)

[[133 165 184 165]
 [133 168 168 165]
 [168 165 132 116]
 [208 168 116  34]]
