In [1]:
import numpy as np
import cv2

In [8]:
frames = []

t = np.array([[100,120,135],
              [102,120,130],
              [101,130,132]])
t1 = np.array([[200,115,140],
               [105,125,210],
               [95,203,195]])
t2 = np.array([[101,120,145],
               [105,130,125],
               [115,135,135]])
frames.append(t)
frames.append(t1)
frames.append(t2)

framesArray = np.stack(frames,axis=0)

background = np.median(framesArray,axis=0).astype(np.uint8)

print(background)

[[101 120 140]
 [105 125 130]
 [101 135 135]]
